import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function About() {
    return (_jsxs("div", { children: [_jsxs("div", { className: "relative bg-gradient-to-br from-[#1a4a2a] via-[#2d6a3f] to-[#1a4a2a] text-center py-6 px-4 overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 opacity-10", style: { backgroundImage: 'repeating-linear-gradient(45deg,transparent,transparent 24px,rgba(200,151,58,.4) 24px,rgba(200,151,58,.4) 26px)' } }), _jsx("h2", { className: "font-['Cormorant_Garamond'] text-[22px] font-bold text-amber-200 relative", children: "\uD83C\uDFDB\uFE0F V\u1EC1 Ch\u00F9a" }), _jsx("div", { className: "w-16 h-px bg-gradient-to-r from-transparent via-amber-400 to-transparent mx-auto my-2.5" }), _jsx("p", { className: "text-[12px] text-amber-200/70 italic relative", children: "Ch\u00F9a Thu\u1EADn Ch\u00E2u \u2013 \u0110\u00E0 N\u1EB5ng" })] }), _jsxs("div", { className: "p-4 flex flex-col gap-4", children: [_jsxs("div", { className: "bg-white rounded-2xl overflow-hidden shadow-md border border-amber-200/40", children: [_jsx("div", { className: "px-4 py-3 bg-amber-50 border-b border-amber-100 text-[13px] font-bold text-[#6b2d00] flex items-center gap-2", children: "\uD83D\uDCCD Th\u00F4ng Tin Li\u00EAn H\u1EC7" }), _jsxs("div", { className: "p-4 space-y-3", children: [[
                                        { ico: '🗺️', label: 'Địa chỉ', val: '220 Đống Đa, Hải Châu, TP. Đà Nẵng' },
                                        { ico: '⏰', label: 'Giờ mở cửa', val: '05:00 – 18:30 hàng ngày' },
                                        { ico: '🙏', label: 'Hệ phái', val: 'Phật Giáo Việt Nam' },
                                    ].map(r => (_jsxs("div", { className: "flex gap-3 items-start pb-3 border-b border-dashed border-amber-100 last:border-none last:pb-0", children: [_jsx("span", { className: "text-xl mt-0.5 flex-shrink-0", children: r.ico }), _jsxs("div", { children: [_jsx("p", { className: "text-[11px] text-stone-400 font-semibold uppercase tracking-wider mb-0.5", children: r.label }), _jsx("p", { className: "text-[13.5px] text-stone-700 font-medium", children: r.val })] })] }, r.label))), _jsx("a", { href: "https://maps.google.com/?q=220+\u0110\u1ED1ng+\u0110a,+H\u1EA3i+Ch\u00E2u,+\u0110\u00E0+N\u1EB5ng", target: "_blank", rel: "noreferrer", className: "flex items-center gap-2 w-full px-4 py-2.5 bg-amber-50 border-2 border-amber-200 rounded-xl text-[13.5px] font-semibold text-[#6b2d00] hover:bg-amber-100 transition mt-1", children: "\uD83D\uDDFA\uFE0F Xem b\u1EA3n \u0111\u1ED3 ch\u1EC9 \u0111\u01B0\u1EDDng" })] })] }), _jsxs("div", { className: "bg-white rounded-2xl overflow-hidden shadow-md border border-amber-200/40", children: [_jsx("div", { className: "px-4 py-3 bg-amber-50 border-b border-amber-100 text-[13px] font-bold text-[#6b2d00]", children: "\uD83D\uDCC5 L\u1ECBch T\u1EE5ng Kinh Th\u01B0\u1EDDng Nh\u1EADt" }), _jsx("div", { className: "p-4 space-y-3", children: [
                                    { time: '05:30', name: 'Tụng kinh sáng', sub: 'Khai chuông, lễ Phật, cầu an' },
                                    { time: '17:30', name: 'Tụng kinh chiều', sub: 'Lễ Phật, hồi hướng công đức' },
                                    { time: 'Chủ Nhật', name: 'Sinh hoạt Phật tử', sub: '08:00 – Pháp thoại & tu học' },
                                    { time: 'Rằm & Mùng 1', name: 'Lễ đặc biệt', sub: 'Cầu an – Cầu siêu – Thí thực' },
                                ].map(s => (_jsxs("div", { className: "flex gap-3 items-start pb-3 border-b border-dashed border-amber-100 last:border-none last:pb-0", children: [_jsx("span", { className: "text-[11px] font-bold text-white bg-gradient-to-r from-orange-600 to-[#7a1c1c] px-2.5 py-1 rounded-lg flex-shrink-0 mt-0.5 min-w-[72px] text-center", children: s.time }), _jsxs("div", { children: [_jsx("p", { className: "text-[13.5px] font-semibold text-stone-800", children: s.name }), _jsx("p", { className: "text-[11.5px] text-stone-400 mt-0.5", children: s.sub })] })] }, s.time))) })] }), _jsxs("div", { className: "bg-white rounded-2xl overflow-hidden shadow-md border border-amber-200/40", children: [_jsx("div", { className: "px-4 py-3 bg-amber-50 border-b border-amber-100 text-[13px] font-bold text-[#6b2d00]", children: "\uD83D\uDCD6 H\u01B0\u1EDBng D\u1EABn S\u1EED D\u1EE5ng App" }), _jsx("div", { className: "p-4 space-y-3", children: [
                                    { ico: '🗓️', text: 'Tab Sự Kiện — xem lịch lễ, khóa tu sắp tới' },
                                    { ico: '🕯️', text: 'Tab Cầu Siêu — gửi danh sách hương linh' },
                                    { ico: '💬', text: 'Tab Hỏi Đáp — trợ lý tự động giải đáp' },
                                ].map(r => (_jsxs("div", { className: "flex gap-3 items-center pb-3 border-b border-dashed border-amber-100 last:border-none last:pb-0", children: [_jsx("span", { className: "text-xl", children: r.ico }), _jsx("p", { className: "text-[13.5px] text-stone-600", children: r.text })] }, r.ico))) })] }), _jsx("p", { className: "text-center text-[12px] text-stone-400 italic py-2", children: "\u2638 Nam m\u00F4 B\u1ED5n S\u01B0 Th\u00EDch Ca M\u00E2u Ni Ph\u1EADt \u2638" })] })] }));
}
